# Numpy

# numpy array method and atributes on net for more info (www.scipy.org)

**numpy tutorial from code with harry**

***numpy tutorial from code with harry***

In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,6,32,7]],np.int64)

In [3]:
myarr[0,3]

7

In [4]:
myarr.shape

(1, 4)

In [5]:
myarr.dtype

dtype('int64')

***we can find more type on net as numpy type reference***

In [6]:
myarr[0,3] =45

**for changing element from array**

In [7]:
myarr

array([[ 3,  6, 32, 45]], dtype=int64)

# Array creation method in numpy

**Conversion from other Python structures (i.e. lists and tuples)

**Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)

**Replicating, joining, or mutating existing arrays

**Reading arrays from disk, either from standard or custom formats

**Creating arrays from raw bytes through the use of strings or buffers

**Use of special library functions (e.g., random)


# Array creation (Conversion from other Python structures)

In [8]:
listarray = np.array([[1,2,3],[5,6,7],[0,3,1]])

In [9]:
listarray

array([[1, 2, 3],
       [5, 6, 7],
       [0, 3, 1]])

In [10]:
listarray.dtype

dtype('int32')

In [11]:
listarray.shape

(3, 3)

In [12]:
listarray.size

9

# Array creation (Intrinsic NumPy array creation functions)

In [13]:
zeros = np.zeros((2,5))

In [14]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
zeros.shape

(2, 5)

In [16]:
rng = np.arange(15)

In [17]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
lspace = np.linspace(1,50,10) #it will make 10 equal parts betwwen 1-50 represent as (1,50,10)

In [19]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [20]:
emp = np.empty((4,6)) 

In [21]:
emp

array([[4.67296746e-307, 1.69121096e-306, 1.86920328e-306,
        1.29060871e-306, 7.56599807e-307, 8.90104239e-307],
       [1.24610383e-306, 1.69118108e-306, 8.06632139e-308,
        1.20160711e-306, 1.69119330e-306, 1.29062229e-306],
       [1.60217812e-306, 1.37961370e-306, 1.69118515e-306,
        1.11258277e-307, 1.05700515e-307, 1.11261774e-306],
       [1.29060871e-306, 8.34424766e-308, 8.34445138e-308,
        1.37959129e-306, 1.02360528e-306, 2.46155235e-312]])

In [22]:
emp_like = np.empty_like(lspace)

In [23]:
emp_like

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [24]:
ide = np.identity(45)

In [25]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [26]:
ide.shape

(45, 45)

In [27]:
arr = np.arange(99)

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [29]:
arr =arr.reshape(3,33)

In [30]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [31]:
arr = arr.ravel()

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [33]:
arr.shape

(99,)

In [34]:
arr[5]

5

In [35]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [36]:
ar = np.array(x)

In [37]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [38]:
ar.sum(axis=1) #adding in side direction 

array([ 6, 15,  8])

In [39]:
ar.sum(axis=0) #adding in downword direction 

array([12,  8,  9])

In [40]:
ar.T #transpose

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [41]:
ar.flat

In [42]:
for item in ar.flat: #print all element in one line
    print(item)

1
2
3
4
5
6
7
1
0


In [43]:
ar.ndim #number of dimensions 

2

In [44]:
ar.size

9

In [45]:
ar.nbytes

36

In [46]:
one = np.array([1,3,4,634,2])

In [47]:
one.argmax() #shows the location of maximum value in array

3

In [48]:
one.argmin() #min value location


0

In [49]:
one.argsort() #orger of elemet sorted low-high

array([0, 4, 1, 2, 3], dtype=int64)

In [50]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [51]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [52]:
ar.argmin()

8

In [53]:
ar.argmax()

6

In [54]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [55]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [56]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [57]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [58]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [59]:
ar2 = np.array([[1, 2, 1],
                [4, 0, 6],
                [8, 1, 0]])

In [60]:
ar+ar2 #adding array  matrix

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [61]:
ar*ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [62]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [63]:
ar.sum()

29

In [64]:
ar.max()

7

In [65]:
ar.min()

0

In [66]:
#find element in array
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [67]:
type(np.where(ar>5))

tuple

In [68]:
np.count_nonzero(ar)

8

In [69]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [70]:
ar[1,2]=0

In [71]:
import sys

In [72]:
py_ar = [0,4,55,2]

In [73]:
np_ar = np.array(py_ar)

In [74]:
sys.getsizeof(1)

28

In [75]:
sys.getsizeof(1) * len(py_ar)

112

In [76]:
np_ar.itemsize * np_ar.size

16

In [77]:
np_ar.tolist()

[0, 4, 55, 2]